#!/usr/bin/env python3
"""Data-only synchronizer for the historic Videha Scholar Research Book.

The Book's publication shell is intentionally hand-preserved.  The canonical source
for article membership is research/data/articles.json.  This script may only:
  * insert inventory records missing from Annex 1 (author-order table),
  * insert the same records into Annex 2 (genre/classification tables),
  * renumber those data tables after insertion,
  * refresh source-derived corpus/provenance metadata.
It never regenerates or replaces the page shell, accessibility controls, translator,
navigation, CSS, scripts, headings, or existing article-row contents.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from pathlib import Path, PurePosixPath
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "research" / "data" / "articles.json"
OUTPUT = ROOT / "research" / "videha-scholar-research-book.html"
OFFICIAL = "https://www.videha.co.in/"
MIRROR = "https://videha-ejournal.github.io/videha/"
ARCHIVE_EXPLORER = MIRROR + "videha-archive-explorer.html?issue="
GENERATED_MARKER = "GENERATED BY scholar-tools/build_research_book.py FROM research/data/articles.json"

SHELL_MARKERS = (
    "विदेह शोध-लेख : अंक १ सँ",
    "VIDEHA Home · www.videha.co.in",
    "GitHub Home · videha-ejournal.github.io/videha",
    'id="videha-tts-toggle"',
    'id="book-search"',
    'class="back-top"',
    "videha-tts.js",
    "videha-translate.js",
    "videha-access.js",
    'aria-label="पृष्ठ सुनबाक, अनुवाद आ सहायक तकनीक नियंत्रण"',
    "अनुलग्नक १ : लेखकानुक्रमेण सम्पूर्ण सूची",
    "अनुलग्नक २ : विधावार सम्पूर्ण सूची",
)

DEVANAGARI_DIGITS = str.maketrans("0123456789", "०१२३४५६७८९")
HONORIFIC_RE = re.compile(
    r"^(?:(?:dr|prof|professor)\.?\s+|(?:डॉ|डा|डाॅ|प्रो|श्री|श्रीमती)\.?\s+)", re.I
)


def as_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        return "; ".join(v for item in value if (v := as_text(item)))
    if isinstance(value, dict):
        for key in ("name", "title", "label", "value"):
            if value.get(key):
                return as_text(value[key])
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value).strip()


def canonical_path(value: str) -> str:
    value = unquote(as_text(value)).replace("\\", "/").strip()
    if not value:
        return ""
    parsed = urlparse(value)
    if parsed.scheme and parsed.netloc:
        value = unquote(parsed.path)
    value = value.split("#", 1)[0].split("?", 1)[0].lstrip("/")
    if value.startswith("videha/"):
        value = value[len("videha/"):]
    if value.startswith("research/"):
        return str(PurePosixPath(value))
    if value.endswith((".htm", ".html")):
        return str(PurePosixPath("research") / PurePosixPath(value))
    return ""


def href_path(href: str) -> str:
    href = html.unescape(href).strip()
    if not href or href.startswith(("#", "mailto:", "javascript:", "tel:")):
        return ""
    parsed = urlparse(href)
    if parsed.scheme and parsed.netloc:
        host = parsed.netloc.casefold()
        if host not in {"www.videha.co.in", "videha.co.in", "videha-ejournal.github.io"}:
            return ""
        value = unquote(parsed.path).lstrip("/")
        if host == "videha-ejournal.github.io" and value.startswith("videha/"):
            value = value[len("videha/"):]
        return canonical_path(value)
    return canonical_path(href)


def load_inventory():
    raw = SOURCE.read_bytes()
    payload = json.loads(raw.decode("utf-8"))
    articles = payload.get("articles")
    if not isinstance(articles, list):
        raise SystemExit("articles.json must contain an articles list")
    declared = payload.get("count")
    if declared is not None and int(declared) != len(articles):
        raise SystemExit(f"Inventory count mismatch: declared={declared}, actual={len(articles)}")
    records = []
    for article in articles:
        path = canonical_path(article.get("path", ""))
        if not path:
            raise SystemExit(f"Invalid article path: {article.get('path')!r}")
        records.append((path, article))
    paths = [p for p, _ in records]
    if len(paths) != len(set(paths)):
        raise SystemExit("Duplicate canonical paths in articles.json")
    return raw, records


def assert_shell(text: str) -> None:
    missing = [marker for marker in SHELL_MARKERS if marker not in text]
    if missing:
        raise SystemExit("Historic Research Book shell is damaged or replaced: " + repr(missing))


def annex_boundaries(text: str):
    a1 = re.search(r"(?is)<h2\b[^>]*>\s*अनुलग्नक\s*१\s*:\s*लेखकानुक्रमेण\s*सम्पूर्ण\s*सूची\s*</h2>", text)
    a2 = re.search(r"(?is)<h2\b[^>]*>\s*अनुलग्नक\s*२\s*:\s*विधावार\s*सम्पूर्ण\s*सूची\s*</h2>", text)
    if not a1 or not a2 or a1.start() >= a2.start():
        raise SystemExit("Historic Research Book annex boundaries not found")
    return a1, a2


def first_table(segment: str):
    table = re.search(r"(?is)<table\b[^>]*>.*?</table>", segment)
    if not table:
        raise SystemExit("Expected Book table not found")
    return table


def tbody_parts(table_html: str):
    m = re.search(r"(?is)(<tbody\b[^>]*>)(.*?)(</tbody>)", table_html)
    if not m:
        raise SystemExit("Expected tbody not found")
    return m


def rows_from(tbody_inner: str) -> list[str]:
    return re.findall(r"(?is)<tr\b[^>]*>.*?</tr>", tbody_inner)


def paths_in_rows(rows: list[str], inventory: set[str]) -> set[str]:
    found: set[str] = set()
    for row in rows:
        for href in re.findall(r"(?is)\bhref\s*=\s*[\"']([^\"']+)[\"']", row):
            path = href_path(href)
            if path in inventory:
                found.add(path)
                break
    return found


def row_article_path(row: str) -> str:
    """Return the canonical research article path referenced by a Book row."""
    attr = re.search(r'(?is)\bdata-source-path=["\']([^"\']+)["\']', row)
    if attr:
        path = canonical_path(html.unescape(attr.group(1)))
        if path:
            return path
    for href in re.findall(r'(?is)\bhref\s*=\s*["\']([^"\']+)["\']', row):
        path = href_path(href)
        if re.match(r"^research/\d{4}/", path):
            return path
    return ""


def prune_annex1(text: str, known: set[str]) -> tuple[str, list[str]]:
    a1, a2 = annex_boundaries(text)
    segment = text[a1.end():a2.start()]
    table_match = first_table(segment)
    table = table_match.group(0)
    body = tbody_parts(table)
    rows = rows_from(body.group(2))
    kept, removed = [], []
    for row in rows:
        path = row_article_path(row)
        if not path:
            raise SystemExit("Cannot identify an Annex 1 article row while pruning stale records")
        if path in known:
            kept.append(row)
        else:
            removed.append(path)
    kept = renumber_rows(kept)
    new_table = table[:body.start(2)] + "".join(kept) + table[body.end(2):]
    new_segment = segment[:table_match.start()] + new_table + segment[table_match.end():]
    return text[:a1.end()] + new_segment + text[a2.start():], removed


def prune_annex2(text: str, known: set[str]) -> tuple[str, list[str]]:
    _, a2 = annex_boundaries(text)
    tail = text[a2.end():]
    stop = re.search(r'(?is)<[^>]+\bclass=["\'][^"\']*\bback-top\b[^"\']*["\'][^>]*>|<script\b', tail)
    if not stop:
        raise SystemExit("Cannot find safe Annex 2 pruning boundary")
    segment = tail[:stop.start()]
    rest = tail[stop.start():]
    pattern = re.compile(
        r"(?is)(<h3\b[^>]*>.*?\()(\d+)(\)\s*</h3>\s*<table\b[^>]*>.*?<tbody\b[^>]*>)(.*?)(</tbody>\s*</table>)"
    )
    removed: list[str] = []
    seen_sections = 0

    def repl(match):
        nonlocal seen_sections
        seen_sections += 1
        rows = rows_from(match.group(4))
        kept = []
        for row in rows:
            path = row_article_path(row)
            if not path:
                raise SystemExit("Cannot identify an Annex 2 article row while pruning stale records")
            if path in known:
                kept.append(row)
            else:
                removed.append(path)
        if not kept:
            return ""
        kept = renumber_rows(kept)
        return match.group(1) + str(len(kept)) + match.group(3) + "".join(kept) + match.group(5)

    new_segment = pattern.sub(repl, segment)
    if not seen_sections:
        raise SystemExit("No Annex 2 genre sections found while pruning stale records")
    return text[:a2.end()] + new_segment + rest, removed


def plain(fragment: str) -> str:
    return " ".join(html.unescape(re.sub(r"(?is)<[^>]+>", " ", fragment)).split())


def row_author(row: str) -> str:
    cells = re.findall(r"(?is)<td\b[^>]*>(.*?)</td>", row)
    return plain(cells[1]) if len(cells) >= 2 else ""


def author_key(name: str) -> str:
    value = " ".join(name.split())
    value = HONORIFIC_RE.sub("", value).strip()
    return value.casefold()


def insert_row_authorwise(rows: list[str], new_row: str, author: str) -> None:
    target = " ".join(author.split()).casefold()
    same = [i for i, row in enumerate(rows) if " ".join(row_author(row).split()).casefold() == target]
    if same:
        rows.insert(same[-1] + 1, new_row)
        return
    key = author_key(author)
    for i, row in enumerate(rows):
        existing = author_key(row_author(row))
        if existing and existing > key:
            rows.insert(i, new_row)
            return
    rows.append(new_row)


def renumber_rows(rows: list[str]) -> list[str]:
    out = []
    for number, row in enumerate(rows, 1):
        changed, n = re.subn(
            r"(?is)(<tr\b[^>]*>\s*<td\b[^>]*>)\s*\d+\s*(</td>)",
            lambda m: m.group(1) + str(number) + m.group(2),
            row,
            count=1,
        )
        if n != 1:
            raise SystemExit(f"Could not renumber a Book row at position {number}")
        out.append(changed)
    return out


def article_author(article) -> str:
    return as_text(article.get("authors")) or as_text(article.get("author"))


def article_url(path: str, article) -> str:
    url = as_text(article.get("url"))
    if url.startswith(("https://www.videha.co.in/", "http://www.videha.co.in/")):
        return url.replace("http://", "https://", 1)
    return OFFICIAL + path


def article_category(article) -> str:
    return as_text(article.get("genre")) or as_text(article.get("classification")) or "Scholarly article"


def article_topics(article) -> str:
    keywords = as_text(article.get("keywords"))
    return keywords or as_text(article.get("classification")) or article_category(article)


def page_label(article) -> str:
    start = as_text(article.get("page_start"))
    end = as_text(article.get("page_end"))
    if start and end:
        return start if start == end else f"{start}–{end}"
    if start:
        return start
    title = as_text(article.get("title"))
    match = re.search(r"पृष्ठ\s*([०-९0-9]+)\s*[-–—]\s*([०-९0-9]+)", title)
    if match:
        return f"{match.group(1)}–{match.group(2)}"
    match = re.search(r"पृष्ठ\s*([०-९0-9]+)", title)
    return match.group(1) if match else "—"


def issue_cell(article) -> str:
    issue = as_text(article.get("issue"))
    date = as_text(article.get("publication_date")) or as_text(article.get("date"))
    label = html.escape(f"अंक {issue}") if issue else "अंक"
    if issue:
        body = f'<a href="{html.escape(ARCHIVE_EXPLORER + issue, quote=True)}">{label}</a>'
    else:
        body = label
    return body + (f" · {html.escape(date)}" if date else "")


def render_author_row(path: str, article) -> str:
    author = article_author(article)
    title = as_text(article.get("title")) or Path(path).stem
    return (
        f'<tr data-source-path="{html.escape(path, quote=True)}"><td>0</td>'
        f"<td>{html.escape(author)}</td>"
        f'<td><a href="{html.escape(article_url(path, article), quote=True)}">{html.escape(title)}</a></td>'
        f"<td>{html.escape(article_category(article))}</td>"
        f"<td>{html.escape(as_text(article.get('language')))}</td>"
        f"<td>{issue_cell(article)}</td>"
        f"<td>{html.escape(article_topics(article))}</td>"
        f"<td>{html.escape(page_label(article))}</td></tr>"
    )


def render_genre_row(path: str, article) -> str:
    author = article_author(article)
    title = as_text(article.get("title")) or Path(path).stem
    return (
        "<tr><td>0</td>"
        f"<td>{html.escape(author)}</td>"
        f'<td><a href="{html.escape(article_url(path, article), quote=True)}">{html.escape(title)}</a></td>'
        f"<td>{html.escape(as_text(article.get('language')))}</td>"
        f"<td>{issue_cell(article)}</td>"
        f"<td>{html.escape(article_topics(article))}</td>"
        f"<td>{html.escape(page_label(article))}</td></tr>"
    )


def sync_annex1(text: str, missing: list[tuple[str, dict]]) -> str:
    a1, a2 = annex_boundaries(text)
    segment = text[a1.end():a2.start()]
    table_match = first_table(segment)
    table = table_match.group(0)
    body = tbody_parts(table)
    rows = rows_from(body.group(2))
    for path, article in missing:
        insert_row_authorwise(rows, render_author_row(path, article), article_author(article))
    rows = renumber_rows(rows)
    new_table = table[:body.start(2)] + "".join(rows) + table[body.end(2):]
    new_segment = segment[:table_match.start()] + new_table + segment[table_match.end():]
    return text[:a1.end()] + new_segment + text[a2.start():]


def genre_section_pattern(category: str):
    label = re.escape(html.escape(category))
    return re.compile(
        rf"(?is)(<h3\b[^>]*>\s*{label}\s*\()(\d+)(\)\s*</h3>\s*<table\b[^>]*>.*?<tbody\b[^>]*>)(.*?)(</tbody>\s*</table>)"
    )


def new_genre_section(category: str, additions: list[tuple[str, dict]]) -> str:
    rows = [render_genre_row(path, article) for path, article in additions]
    rows = renumber_rows(rows)
    return (
        f"<h3>{html.escape(category)} ({len(rows)})</h3>"
        "<table><thead><tr><th>क्रम</th><th>लेखक</th><th>लेख</th><th>भाषा</th>"
        "<th>अंक · तिथि</th><th>वर्गीकरण</th><th>पृष्ठ</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def sync_annex2(text: str, missing: list[tuple[str, dict]]) -> str:
    grouped: dict[str, list[tuple[str, dict]]] = {}
    for path, article in missing:
        grouped.setdefault(article_category(article), []).append((path, article))

    for category, additions in grouped.items():
        pattern = genre_section_pattern(category)
        match = pattern.search(text)
        if match:
            rows = rows_from(match.group(4))
            for path, article in additions:
                insert_row_authorwise(rows, render_genre_row(path, article), article_author(article))
            rows = renumber_rows(rows)
            replacement = match.group(1) + str(len(rows)) + match.group(3) + "".join(rows) + match.group(5)
            text = text[:match.start()] + replacement + text[match.end():]
            continue

        # New classification: append only at the end of Annex 2, immediately before
        # the historic back-to-top control/scripts.  Existing sections are untouched.
        _, a2 = annex_boundaries(text)
        tail = text[a2.end():]
        stop = re.search(r"(?is)<[^>]+\bclass=[\"'][^\"']*\bback-top\b[^\"']*[\"'][^>]*>|<script\b", tail)
        if not stop:
            raise SystemExit(f"Cannot find safe Annex 2 insertion point for {category!r}")
        pos = a2.end() + stop.start()
        section = new_genre_section(category, additions)
        text = text[:pos] + section + text[pos:]
    return text


def author_annex_rows(text: str) -> list[str]:
    a1, a2 = annex_boundaries(text)
    segment = text[a1.end():a2.start()]
    table = first_table(segment).group(0)
    return rows_from(tbody_parts(table).group(2))


def genre_annex_rows(text: str) -> list[str]:
    _, a2 = annex_boundaries(text)
    tail = text[a2.end():]
    # Stop before scripts/back-top to avoid any unrelated later table.
    stop = re.search(r"(?is)<[^>]+\bclass=[\"'][^\"']*\bback-top\b[^\"']*[\"'][^>]*>|<script\b", tail)
    segment = tail[:stop.start()] if stop else tail
    out: list[str] = []
    for inner in re.findall(r"(?is)<tbody\b[^>]*>(.*?)</tbody>", segment):
        out.extend(rows_from(inner))
    return out


def refresh_counts_and_provenance(text: str, raw: bytes, records: list[tuple[str, dict]]) -> str:
    if GENERATED_MARKER not in text:
        text = text.replace("<!doctype html>", f"<!doctype html>\n<!-- {GENERATED_MARKER} -->", 1)
    count = len(records)
    # Visible search status and the inline search script both use the corpus phrase.
    text = re.sub(r"(?<![0-9])\d+\s*लेख", f"{count} लेख", text)
    text = re.sub(r'("numberOfItems"\s*:\s*)\d+', rf"\g<1>{count}", text)

    # Keep the issue range source-derived as well (the restored shell already says 448;
    # this also repairs any stale JSON-LD name that still said 447).
    issues = [int(as_text(a.get("issue"))) for _, a in records if as_text(a.get("issue")).isdigit()]
    if issues:
        max_issue_deva = str(max(issues)).translate(DEVANAGARI_DIGITS)
        text = re.sub(r"अंक\s*१\s*सँ\s*[०-९]+\s*धरि", f"अंक १ सँ {max_issue_deva} धरि", text)

    source_sha = hashlib.sha256(raw).hexdigest()
    provenance = (
        '<meta name="videha-article-source" content="research/data/articles.json">\n'
        f'<meta name="videha-article-source-sha256" content="{source_sha}">\n'
        f'<meta name="videha-article-count" content="{count}">'
    )
    text = re.sub(
        r'(?is)\s*<meta\s+name=["\']videha-article-source["\'][^>]*>\s*'
        r'<meta\s+name=["\']videha-article-source-sha256["\'][^>]*>\s*'
        r'<meta\s+name=["\']videha-article-count["\'][^>]*>',
        "\n" + provenance,
        text,
        count=1,
    )
    if 'name="videha-article-source"' not in text and "name='videha-article-source'" not in text:
        text = re.sub(r"(?i)</head>", provenance + "\n</head>", text, count=1)
    return text


def inventory_paths(rows: list[str], known: set[str]) -> set[str]:
    return paths_in_rows(rows, known)


def verify(text: str, raw: bytes, records: list[tuple[str, dict]]) -> None:
    assert_shell(text)
    if GENERATED_MARKER not in text:
        raise SystemExit("Research Book generation marker missing")
    if text.count('data-source-path="') != len(records):
        raise SystemExit("Research Book data-source-path count differs from canonical inventory")
    known = {p for p, _ in records}
    author_rows = author_annex_rows(text)
    genre_rows = genre_annex_rows(text)
    if len(author_rows) != len(records):
        raise SystemExit(f"Annex 1 row mismatch: {len(author_rows)} != {len(records)}")
    if len(genre_rows) != len(records):
        raise SystemExit(f"Annex 2 row mismatch: {len(genre_rows)} != {len(records)}")
    author_paths = inventory_paths(author_rows, known)
    genre_paths = inventory_paths(genre_rows, known)
    if author_paths != known:
        raise SystemExit(f"Annex 1 path mismatch: missing={len(known-author_paths)}")
    if genre_paths != known:
        raise SystemExit(f"Annex 2 path mismatch: missing={len(known-genre_paths)}")
    source_sha = hashlib.sha256(raw).hexdigest()
    required = (
        '<meta name="videha-article-source" content="research/data/articles.json">',
        f'<meta name="videha-article-source-sha256" content="{source_sha}">',
        f'<meta name="videha-article-count" content="{len(records)}">',
    )
    missing = [x for x in required if x not in text]
    if missing:
        raise SystemExit(f"Research Book provenance mismatch: {missing}")


def synchronize(text: str, raw: bytes, records: list[tuple[str, dict]]):
    assert_shell(text)
    known = {p for p, _ in records}

    # Explicit editorial exclusions can legitimately shrink the canonical inventory.
    # Remove only Book rows whose own article URL/path is no longer canonical.
    rendered, removed_author = prune_annex1(text, known)
    rendered, removed_genre = prune_annex2(rendered, known)
    if set(removed_author) != set(removed_genre):
        raise SystemExit(
            "Research Book stale-row pruning differs between annexes: "
            f"author={sorted(set(removed_author))}, genre={sorted(set(removed_genre))}"
        )

    existing_author_rows = author_annex_rows(rendered)
    existing_paths = inventory_paths(existing_author_rows, known)
    if len(existing_paths) != len(existing_author_rows):
        raise SystemExit(
            f"Research Book Annex 1 contains unmapped or duplicate rows after pruning: "
            f"rows={len(existing_author_rows)}, matched={len(existing_paths)}"
        )
    missing = [(p, a) for p, a in records if p not in existing_paths]
    if len(existing_paths) + len(missing) != len(records):
        raise SystemExit("Research Book inventory reconciliation failed")

    if missing:
        rendered = sync_annex1(rendered, missing)
        rendered = sync_annex2(rendered, missing)
    rendered = refresh_counts_and_provenance(rendered, raw, records)
    verify(rendered, raw, records)
    return rendered, missing, sorted(set(removed_author))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    raw, records = load_inventory()
    current = OUTPUT.read_text(encoding="utf-8")
    if args.check:
        verify(current, raw, records)
        print(f"Research Book verified from canonical source: {len(records)} rows in each annex; historic shell intact")
        return

    rendered, missing, removed = synchronize(current, raw, records)
    if rendered != current:
        OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"SOURCE_COUNT={len(records)}")
    print(f"REMOVED_STALE={len(removed)}")
    for path in removed:
        print("REMOVED:", path)
    print(f"MISSING_BEFORE={len(missing)}")
    for path, article in missing:
        print("ADDED:", path, "::", article_author(article), "::", as_text(article.get("title")), "::", article_category(article))
    print(f"FINAL_COUNT={len(records)}")


if __name__ == "__main__":
    main()
